# Copyright (c) 2025 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: antmicro
      url-base: https://github.com/antmicro

  projects:
    - name: kenning-zephyr-runtime
      remote: antmicro
      revision: main
      import:
        path-allowlist:
          - dlpack
          - tvm
          - tflite-micro

    - name: zephyr
      remote: zephyrproject-rtos
      revision: 732a3a5c66553969ea01bacec19e2820b9d6b2e2
      import:
        path-allowlist:
          - modules/debug/*
          - modules/hal/*
          - modules/lib/*
          - modules/tee/tf-m/*

    - name: zephelin
      remote: antmicro
      revision: main
      import: true
